version: "3"
services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    ports:
      - 9042:9042
  postgres:
    container_name: postgres
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_WALDIR: /pg_waldir
      PGDATA: /pg_data
    ports:
      - 5432:5432
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.10.0
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "./.selenoid:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:1.10.0
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]